name: "TAP Job Summary"
description: "Creates a summary for Test Anything Protocol (TAP) reports."
author: "Niklas Mollenhauer"
inputs:
  path:
    required: false
    default: "**/*.tap"
    description: Path to the TAP file(s).

  show-successful:
    required: false
    default: "false"
    description: Whether to include successful tests oin the test summary table.

runs:
  using: "node20"
  main: "index.js"

branding:
  icon: check-square
  color: green
